name: app
description: "Sistema de busca semântica com IA para análise de dados, chat interativo e geração automática de boletins por email - Projeto Javali."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Essenciais para UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Navegação
  go_router: ^13.2.0
  
  # Rede (para futuras integrações com API)
  dio: ^5.4.0
  http: ^1.1.0
  
  # Internacionalização
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/